# Generated by Django 5.1.6 on 2025-02-27 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="driver",
            new_name="drivers",
        ),
    ]
