# Generated by Django 5.1.6 on 2025-02-28 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0002_rename_driver_car_drivers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="drivers",
            new_name="driver",
        ),
    ]
