# Generated by Django 5.1.6 on 2025-02-28 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0003_rename_drivers_car_driver"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("last_name", "first_name")},
        ),
    ]
