# Generated by Django 5.1.6 on 2025-02-28 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0005_alter_driver_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="driver",
            options={"ordering": ("last_name", "first_name")},
        ),
    ]
